"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type DreamAnalysis = { theme: string; overview: string; symbols: { name: string; evidence: string; possibility: string }[]; psychology: string[]; traditional: string[]; questions: string[]; synthesis: string; };
type CreativeMode = "image" | "novel" | "film";
type Dream = { id: string; title: string; date: string; timestamp: number; content: string; summary: string; emotion: string; tags: string[]; analysis: DreamAnalysis; };
type SpeechRecognitionEventLike = Event & { results: ArrayLike<{ 0: { transcript: string }; isFinal: boolean }> };
type SpeechRecognitionErrorLike = Event & { error?: string };
type SpeechRecognitionLike = { lang: string; interimResults: boolean; continuous: boolean; start: () => void; stop: () => void; abort: () => void; onresult: ((event: SpeechRecognitionEventLike) => void) | null; onerror: ((event: SpeechRecognitionErrorLike) => void) | null; onend: (() => void) | null; };
type SpeechRecognitionCtor = new () => SpeechRecognitionLike;

const STORAGE_KEY = "mengyu-dreams-v2";
const DRAFT_KEY = "mengyu-draft-v2";
const stopWords = new Set(["梦见","梦到","然后","后来","最后","一个","一些","那里","这里","自己","我们","他们","感觉","好像","突然","一直","正在","看到","看见","里面","时候","什么","没有","还是"]);
const symbolRules = [
  { key:"狗", label:"狗 / 动物", idea:"关系中的亲近、忠诚、追逐或本能反应" }, { key:"猫", label:"猫 / 动物", idea:"独立、敏感、警觉或难以控制的亲密距离" },
  { key:"水", label:"水", idea:"情绪的流动、未知感或需要被容纳的感受" }, { key:"海", label:"海", idea:"更辽阔、难以穷尽的情绪与可能性" },
  { key:"桥", label:"桥", idea:"过渡、连接、选择，或从一种状态进入另一种状态" }, { key:"车站", label:"车站", idea:"等待、启程、错过，或人生节奏的转换" },
  { key:"火车", label:"列车", idea:"被既定轨道带动的进程与时间压力" }, { key:"房", label:"房屋", idea:"内在空间、家庭经验、隐私与安全感" },
  { key:"学校", label:"学校", idea:"评价、学习、规则和过去形成的标准" }, { key:"考试", label:"考试", idea:"被评估、准备不足或对结果的在意" },
  { key:"高考", label:"高考", idea:"高压评价、关键选择与人生分岔" }, { key:"追", label:"追逐", idea:"尚未正面处理的压力、目标或关系张力" },
  { key:"飞", label:"飞行", idea:"自由、脱离限制，或对失控的复杂感受" }, { key:"坠", label:"坠落", idea:"失去支撑、控制感下降或对失败的担心" },
  { key:"蛇", label:"蛇", idea:"变化、本能、危险感，或难以命名的吸引力" }, { key:"月", label:"月亮", idea:"夜间情绪、直觉、距离感与温柔的照见" },
  { key:"门", label:"门", idea:"机会、边界，以及是否准备进入新阶段" }, { key:"钥匙", label:"钥匙", idea:"开启、解决问题，或重新取回某种能力" },
  { key:"死", label:"死亡", idea:"结束、告别与身份变化；通常不等于现实预兆" }, { key:"迷路", label:"迷路", idea:"方向感不足、选择过多或暂时缺少确定答案" },
];
function cleanText(value:string){ return value.replace(/\s+/g," ").trim(); }
function splitPhrases(text:string){ return cleanText(text).split(/[。！？!?；;\n，,、]/).map(p=>p.trim()).filter(Boolean); }
function extractTags(text:string){ const found=symbolRules.filter(r=>text.includes(r.key)).map(r=>r.label); const words=text.match(/[\u4e00-\u9fff]{2,6}/g)??[]; for(const word of words){ const tidy=word.replace(/^(我|梦见|梦到|一只|一个|两个|两只|突然|后来)/,""); if(tidy.length>=2&&!stopWords.has(tidy)&&!found.some(i=>i.includes(tidy))) found.push(tidy); if(found.length>=4) break; } return [...new Set(found)].slice(0,4); }
function titleFromContent(text:string){ const phrases=splitPhrases(text), tags=extractTags(text); const action=text.includes("追")?"追逐":text.includes("飞")?"飞行":text.includes("坠")?"坠落":text.includes("考试")||text.includes("高考")?"考场":text.includes("迷路")?"迷路":text.includes("回家")?"归途":""; if(tags.length>=2)return `${tags[0]}与${tags[1]}${action?`的${action}`:""}`.slice(0,18); if(tags.length===1)return `${tags[0]}${action?`的${action}`:"之梦"}`.slice(0,18); const first=(phrases[0]||text).replace(/^(昨晚|今天|我|梦见|梦到)+/,"").trim(); return first.slice(0,14)||"未命名的梦"; }
function analyzeContent(text:string,emotion:string):DreamAnalysis{ const phrases=splitPhrases(text),matches=symbolRules.filter(r=>text.includes(r.key)).slice(0,5),tags=extractTags(text); const symbols=matches.length?matches.map(rule=>({name:rule.label,evidence:(phrases.find(p=>p.includes(rule.key))||`梦中出现了“${rule.label}”`).slice(0,64),possibility:rule.idea})):[{name:tags[0]||"核心场景",evidence:(phrases[0]||text).slice(0,64),possibility:"它可能是近期经验的重新组合，也可能承载只有你自己知道的个人联想"}]; const pressure=/考试|高考|迟到|追|逃|工作|领导|作业/.test(text),transition=/桥|门|车站|火车|搬家|毕业|离开|回家|道路/.test(text),relationship=/朋友|家人|妈妈|爸爸|孩子|恋人|同事|狗|猫|人群/.test(text); const theme=[pressure?"压力与评价":"",transition?"过渡与选择":"",relationship?"关系与边界":""].filter(Boolean).join("、")||`${symbols[0].name}带来的个人联想`; return {theme,overview:`这个梦围绕“${theme}”展开。你记录的主感受是“${emotion}”。梦把${symbols.map(s=>s.name).join("、")}放在同一段叙事里，可能是在整理近期经验，而不是给出固定答案。`,symbols,psychology:[pressure?"梦中出现了追赶、考试或任务类情节，可能对应现实中“需要及时做到、不能失败”的压力。":"梦的叙事更像在整理感受与记忆碎片，重点可放在醒来后最强烈的身体感受上。",transition?"道路、门、桥或车站常形成“从这里到那里”的结构，可以回想近期是否正处在选择或身份变化中。":`“${symbols[0].name}”的意义取决于你的个人经验：现实中最先让你想到的人、地方或事件，比通用象征更重要。`,relationship?"梦里的人或动物未必代表其本身，也可能承载你对亲近、责任、信任或边界的感受。":"梦境分析不能用于诊断；如果它持续造成强烈困扰，可优先照顾睡眠和现实中的安全感。"],traditional:symbols.map(s=>`${s.name}在传统民俗阅读中常被赋予象征意义，但不同地区和文本说法差异很大。对这个梦更稳妥的用法，是把它当作文化联想，而不是吉凶预测。`).slice(0,3),questions:[`现实中，什么最像梦里的“${symbols[0].name}”？`,pressure?"最近哪件事让你觉得正在被追赶、比较或评判？":"醒来后身体最明显的感觉在哪里？",`如果梦可以继续，带着“${emotion}”的你最想改变哪个情节？`],synthesis:`心理探索与文化象征都只能提供假设。这个梦目前最值得保留的线索是“${theme}”，以及你对${symbols.map(s=>s.name).join("、")}的第一手联想。`}; }
function buildDream(content:string,emotion:string,timestamp=Date.now()):Dream{ const cleaned=cleanText(content),date=new Date(timestamp),tags=extractTags(cleaned); return {id:globalThis.crypto?.randomUUID?.()||`${timestamp}-${Math.random()}`,title:titleFromContent(cleaned),date:new Intl.DateTimeFormat("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(date).replace("/","月").replace(" ","日 · "),timestamp,content:cleaned,summary:(splitPhrases(cleaned).slice(0,2).join("，")||cleaned).slice(0,72),emotion,tags:tags.length?tags:[emotion,"梦境"],analysis:analyzeContent(cleaned,emotion)}; }
const SAMPLE_CONTENT="梦见两只小狗一直追着我跑，后来我们一起走进了考场参加高考。";
function getSamples():Dream[]{return [buildDream(SAMPLE_CONTENT,"好奇",Date.now()-86400000)];}
function formatDate(date:Date){return new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long"}).format(date);}

export function DreamApp(){
 const [page,setPage]=useState<"record"|"library"|"insights"|"settings">("record"),[dreams,setDreams]=useState<Dream[]>([]),[text,setText]=useState(""),[emotion,setEmotion]=useState("好奇"),[selected,setSelected]=useState<Dream|null>(null),[analysisTab,setAnalysisTab]=useState<"psychology"|"traditional"|"synthesis">("psychology"),[detailView,setDetailView]=useState<"analysis"|"creative"|"original">("analysis"),[recording,setRecording]=useState(false),[speechSupported,setSpeechSupported]=useState(true),[interim,setInterim]=useState(""),[toast,setToast]=useState(""),[query,setQuery]=useState(""),[hydrated,setHydrated]=useState(false); const recognitionRef=useRef<SpeechRecognitionLike|null>(null),speechBaseRef=useRef(""),loadedRef=useRef(false);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);setDreams(saved?JSON.parse(saved):getSamples());setText(localStorage.getItem(DRAFT_KEY)||"");}catch{setDreams(getSamples());} const scope=window as unknown as {SpeechRecognition?:SpeechRecognitionCtor;webkitSpeechRecognition?:SpeechRecognitionCtor};setSpeechSupported(Boolean(scope.SpeechRecognition||scope.webkitSpeechRecognition));loadedRef.current=true;setHydrated(true);},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(STORAGE_KEY,JSON.stringify(dreams));},[dreams,hydrated]); useEffect(()=>{if(!loadedRef.current)return;const timer=setTimeout(()=>localStorage.setItem(DRAFT_KEY,text),250);return()=>clearTimeout(timer);},[text]); useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),2800);return()=>clearTimeout(timer);},[toast]); useEffect(()=>()=>recognitionRef.current?.abort(),[]);
 const filteredDreams=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?dreams.filter(d=>`${d.title}${d.content}${d.emotion}${d.tags.join("")}`.toLowerCase().includes(needle)):dreams;},[dreams,query]);
 const toggleSpeech=()=>{if(recording){recognitionRef.current?.stop();setRecording(false);return;} const scope=window as unknown as {SpeechRecognition?:SpeechRecognitionCtor;webkitSpeechRecognition?:SpeechRecognitionCtor},Recognition=scope.SpeechRecognition||scope.webkitSpeechRecognition;if(!Recognition){setSpeechSupported(false);setToast("当前浏览器不支持语音识别，请使用 Chrome / Edge，或继续文字输入");return;}try{const recognition=new Recognition();speechBaseRef.current=text.trim();recognition.lang="zh-CN";recognition.interimResults=true;recognition.continuous=true;recognition.onresult=(event)=>{let finalText="",interimText="";for(let i=0;i<event.results.length;i++){const transcript=event.results[i][0]?.transcript||"";if(event.results[i].isFinal)finalText+=transcript;else interimText+=transcript;}if(finalText){const next=[speechBaseRef.current,finalText].filter(Boolean).join(speechBaseRef.current?" ":"");speechBaseRef.current=cleanText(next);setText(speechBaseRef.current);}setInterim(interimText);};recognition.onerror=(event)=>{setRecording(false);setInterim("");setToast(event.error==="not-allowed"?"麦克风权限未开启，请允许后重试":event.error==="no-speech"?"暂时没有识别到声音，请靠近麦克风再试":"语音识别中断了，请重试或继续文字输入");};recognition.onend=()=>{setRecording(false);setInterim("");};recognitionRef.current=recognition;recognition.start();setRecording(true);setToast("正在实时识别，你说的话会写入梦境内容");}catch{setToast("语音识别未能启动，请检查浏览器的麦克风权限");}};
 const analyze=()=>{if(!cleanText(text)){setToast("先写下或说出你记得的梦");return;}const dream=buildDream(text,emotion);setDreams(current=>[dream,...current]);setText("");setInterim("");localStorage.removeItem(DRAFT_KEY);setSelected(dream);setDetailView("analysis");setAnalysisTab("psychology");setToast(`已生成“${dream.title}”的专属分析`);};
 const saveDraft=()=>{localStorage.setItem(DRAFT_KEY,text);setToast(text.trim()?"草稿已保存在这台设备上":"当前没有需要保存的内容");}; const openDream=(dream:Dream)=>{setSelected(dream);setDetailView("analysis");setAnalysisTab("psychology");scrollTo({top:0,behavior:"smooth"});}; const navigate=(next:typeof page)=>{setSelected(null);setPage(next);scrollTo({top:0,behavior:"smooth"});};
 return <main className="app-shell">{toast&&<div className="toast" role="status">{toast}</div>}<header className="topbar"><button className="brand" onClick={()=>navigate("record")} aria-label="返回记录首页"><span className="brand-mark">☾</span><span>梦屿</span></button><span className="privacy-pill">⌾ 仅保存在你的设备</span></header>{selected?<DreamDetail dream={selected} view={detailView} setView={setDetailView} tab={analysisTab} setTab={setAnalysisTab} notify={setToast} onBack={()=>setSelected(null)} onDelete={()=>{setDreams(current=>current.filter(item=>item.id!==selected.id));setSelected(null);setToast("这条梦境已经删除");}}/>:<>{page==="record"&&<RecordPage dreams={dreams} text={text} setText={setText} emotion={emotion} setEmotion={setEmotion} recording={recording} speechSupported={speechSupported} interim={interim} toggleSpeech={toggleSpeech} saveDraft={saveDraft} analyze={analyze} openDream={openDream} showLibrary={()=>navigate("library")}/>} {page==="library"&&<LibraryPage dreams={filteredDreams} query={query} setQuery={setQuery} openDream={openDream}/>} {page==="insights"&&<InsightsPage dreams={dreams}/>} {page==="settings"&&<SettingsPage dreamCount={dreams.length} clearAll={()=>{if(confirm("确定删除这台设备上的全部梦境吗？此操作无法撤销。")){setDreams([]);setText("");localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(DRAFT_KEY);setToast("本机梦境数据已清空");}}}/>}</>}{!selected&&<nav className="bottom-nav" aria-label="主要导航">{[["record","✦","记录"],["library","▤","梦册"],["insights","◌","洞察"],["settings","⚙","设置"]].map(([id,icon,label])=><button key={id} className={page===id?"active":""} onClick={()=>navigate(id as typeof page)}><span>{icon}</span><small>{label}</small></button>)}</nav>}</main>;
}
function RecordPage(props:{dreams:Dream[];text:string;setText:(v:string)=>void;emotion:string;setEmotion:(v:string)=>void;recording:boolean;speechSupported:boolean;interim:string;toggleSpeech:()=>void;saveDraft:()=>void;analyze:()=>void;openDream:(d:Dream)=>void;showLibrary:()=>void;}){const [contextOpen,setContextOpen]=useState(false),[keywordMode,setKeywordMode]=useState(false),recent=props.dreams.slice(0,3);return <><section className="hero"><div className="hero-copy"><div className="eyebrow">醒来后的第一件事</div><h1>梦还在吗？<br/><em>把它留住。</em></h1><p>不急着解释，也不必完整。记下一幅画面、一种感受，或者梦里没有说完的那句话。</p></div><div className="record-card"><div className="date-row"><span>{formatDate(new Date())}</span><span>{props.text?"草稿自动保存":"等待记录"}</span></div>{keywordMode?<input className="keyword-input" value={props.text} onChange={e=>props.setText(e.target.value)} placeholder="月亮、车站、奔跑、害怕……" aria-label="梦境关键词"/>:<textarea value={props.text} onChange={e=>props.setText(e.target.value)} placeholder="我在一个很长的车站里……" aria-label="梦境内容"/>}{props.interim&&<div className="interim">正在识别：{props.interim}</div>}<button className={`voice-button ${props.recording?"recording":""}`} onClick={props.toggleSpeech}><span className="mic">●</span>{props.recording?"停止语音识别":props.speechSupported?"开始实时语音输入":"当前浏览器不支持语音识别"}</button><button className="context-toggle" onClick={()=>setContextOpen(v=>!v)}>{contextOpen?"－ 收起醒来感受":"＋ 添加醒来感受（可选）"}</button>{contextOpen&&<div className="context-panel"><b>醒来时最明显的感受</b><div className="chip-row">{["好奇","平静","焦虑","怀念","喜悦","恐惧"].map(item=><button key={item} className={props.emotion===item?"selected":""} onClick={()=>props.setEmotion(item)}>{item}</button>)}</div></div>}<div className="record-actions"><button onClick={()=>setKeywordMode(v=>!v)}>{keywordMode?"写完整梦境":"只记关键词"}</button><button onClick={props.saveDraft}>保存，继续睡</button></div><button className="analyze-button" onClick={props.analyze}><span>◎</span><span><b>深度分析梦境</b><small>依据你刚刚输入的内容生成专属解读</small></span><span>→</span></button></div></section><section className="recent-section"><div className="section-head"><div><h2>最近的梦</h2><p>每个梦都有自己的名字和线索</p></div><button onClick={props.showLibrary}>查看梦册 →</button></div><div className="dream-grid">{recent.map(dream=><button className="dream-card" key={dream.id} onClick={()=>props.openDream(dream)}><span className="dream-date">{dream.date}</span><h3>{dream.title}</h3><p>{dream.summary}</p><div className="tag-row">{dream.tags.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div></button>)}{!recent.length&&<div className="empty-card">第一段梦正在等你留下。</div>}</div></section></>}
function DreamDetail(props:{dream:Dream;view:"analysis"|"creative"|"original";setView:(v:"analysis"|"creative"|"original")=>void;tab:"psychology"|"traditional"|"synthesis";setTab:(t:"psychology"|"traditional"|"synthesis")=>void;notify:(m:string)=>void;onBack:()=>void;onDelete:()=>void;}){const {dream,tab}=props;return <section className="detail-page"><button className="back-button" onClick={props.onBack}>← 返回</button><div className="detail-hero"><span>{dream.date} · {dream.emotion}</span><h1>{dream.title}</h1><p>{dream.content}</p><div className="tag-row">{dream.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div><div className="detail-tabs"><button className={props.view==="analysis"?"active":""} onClick={()=>props.setView("analysis")}>双轨解读</button><button className={props.view==="creative"?"active":""} onClick={()=>props.setView("creative")}>✦ 梦境创作</button><button className={props.view==="original"?"active":""} onClick={()=>props.setView("original")}>原始记录</button></div>{props.view==="analysis"&&<><div className="analysis-tabs"><button className={tab==="psychology"?"active":""} onClick={()=>props.setTab("psychology")}>心理探索</button><button className={tab==="traditional"?"active":""} onClick={()=>props.setTab("traditional")}>传统梦象</button><button className={tab==="synthesis"?"active":""} onClick={()=>props.setTab("synthesis")}>综合启示</button></div><article className="analysis-report">{tab==="psychology"&&<><div className="report-label">根据这条梦境动态生成</div><h2>{dream.analysis.theme}</h2><p className="lead">{dream.analysis.overview}</p><h3>关键意象与原文依据</h3><div className="symbol-list">{dream.analysis.symbols.map(s=><div key={s.name}><b>{s.name}</b><span>{s.evidence}</span><p>{s.possibility}</p></div>)}</div><h3>可探索的心理假设</h3><ul>{dream.analysis.psychology.map(i=><li key={i}>{i}</li>)}</ul></>}{tab==="traditional"&&<><div className="report-label">文化参考 · 不作吉凶预测</div><h2>{dream.analysis.symbols.map(i=>i.name).join("、")}的民俗联想</h2>{dream.analysis.traditional.map(i=><div className="culture-note" key={i}>{i}</div>)}<p className="boundary">传统梦象缺少统一、可验证的解释体系。本页只保留文化阅读，不将梦境当作现实事件的预言。</p></>}{tab==="synthesis"&&<><div className="report-label">综合阅读 · 保留不确定性</div><h2>把通用象征交还给你的个人经验</h2><p className="lead">{dream.analysis.synthesis}</p><h3>可以继续问自己的问题</h3><div className="question-list">{dream.analysis.questions.map((i,index)=><div key={i}><span>{index+1}</span><p>{i}</p></div>)}</div></>}<div className="boundary"><b>分析边界：</b> 梦境解读不是诊断，也没有唯一答案。页面只依据你保存的这条梦境生成内容。</div></article></>}{props.view==="creative"&&<CreativeStudio dream={dream} notify={props.notify}/>} {props.view==="original"&&<div className="original-card"><div className="report-label">原始梦境 · 不受艺术改编影响</div><p>{dream.content}</p><div className="tag-row"><span>{dream.emotion}</span>{dream.tags.map(t=><span key={t}>{t}</span>)}</div></div>}<button className="delete-button" onClick={props.onDelete}>删除这条梦境</button></section>}

function creativeScenes(dream:Dream){const phrases=splitPhrases(dream.content);const symbols=dream.analysis.symbols;return Array.from({length:3},(_,i)=>({title:symbols[i]?.name||`场景 ${i+1}`,description:(phrases[i]||phrases[0]||dream.summary).slice(0,46),art:i===0?"art-moon":i===1?"art-land":"art-path"}));}
function CreativeStudio({dream,notify}:{dream:Dream;notify:(m:string)=>void}){const [mode,setMode]=useState<CreativeMode>("image");return <div className="creative-space"><div className="creative-toolbar"><div><h2>把“{dream.title}”变成另一种作品</h2><p>所有场景、文字与分镜都从这条梦的原文重新提炼，不会写回心理分析。</p></div><div className="creative-switch"><button className={mode==="image"?"active":""} onClick={()=>setMode("image")}>生成画面</button><button className={mode==="novel"?"active":""} onClick={()=>setMode("novel")}>小说改编</button><button className={mode==="film"?"active":""} onClick={()=>setMode("film")}>电影化</button></div></div>{mode==="image"&&<ImageStudio dream={dream} notify={notify}/>} {mode==="novel"&&<NovelStudio dream={dream} notify={notify}/>} {mode==="film"&&<FilmStudio dream={dream} notify={notify}/>}</div>}
function downloadDreamArtwork(dream:Dream,scene:{title:string;description:string},style:string,ratio:string){const canvas=document.createElement("canvas");const size=ratio==="9:16"?[900,1600]:ratio==="1:1"?[1200,1200]:[1600,900];canvas.width=size[0];canvas.height=size[1];const ctx=canvas.getContext("2d");if(!ctx)return;const seed=[...`${dream.title}${scene.title}`].reduce((n,c)=>n+c.charCodeAt(0),0),hue=seed%360;const gradient=ctx.createLinearGradient(0,0,canvas.width,canvas.height);gradient.addColorStop(0,`hsl(${hue} 30% 18%)`);gradient.addColorStop(.55,`hsl(${(hue+42)%360} 28% 38%)`);gradient.addColorStop(1,`hsl(${(hue+85)%360} 38% 72%)`);ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<18;i++){ctx.beginPath();ctx.fillStyle=`rgba(255,245,210,${.025+(i%5)*.012})`;ctx.arc((seed*(i+3)*17)%canvas.width,(seed*(i+7)*11)%canvas.height,35+(i%6)*28,0,Math.PI*2);ctx.fill()}ctx.fillStyle="rgba(8,25,22,.58)";ctx.fillRect(0,canvas.height*.62,canvas.width,canvas.height*.38);ctx.fillStyle="#fff8df";ctx.font=`600 ${Math.round(canvas.width*.052)}px serif`;ctx.fillText(scene.title,canvas.width*.07,canvas.height*.73);ctx.font=`400 ${Math.round(canvas.width*.024)}px sans-serif`;const words=[...scene.description];let line="",y=canvas.height*.81;for(const char of words){if(ctx.measureText(line+char).width>canvas.width*.82){ctx.fillText(line,canvas.width*.07,y);line=char;y+=canvas.width*.038}else line+=char}if(line)ctx.fillText(line,canvas.width*.07,y);ctx.font=`400 ${Math.round(canvas.width*.016)}px sans-serif`;ctx.fillStyle="rgba(255,255,255,.72)";ctx.fillText(`${style} · 源自《${dream.title}》 · 本机生成`,canvas.width*.07,canvas.height*.94);canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${dream.title}-${scene.title}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},"image/png")}
function ImageStudio({dream,notify}:{dream:Dream;notify:(m:string)=>void}){const scenes=creativeScenes(dream),[selected,setSelected]=useState(0),[adaptation,setAdaptation]=useState("合理补全"),[style,setStyle]=useState("梦幻电影感"),[ratio,setRatio]=useState("16:9"),[done,setDone]=useState(false),[generating,setGenerating]=useState(false);const generate=()=>{setGenerating(true);setDone(false);setTimeout(()=>{setGenerating(false);setDone(true);notify(`已根据“${scenes[selected].title}”生成创作草图预览`);},900)};return <div className="studio"><div className="studio-main"><div className="studio-title"><h3>选择梦中的一幕</h3><small>来源：当前梦境原文</small></div><div className="scene-grid">{scenes.map((scene,i)=><button className={`scene-card ${selected===i?"selected":""}`} key={scene.title} onClick={()=>setSelected(i)}><div className={`scene-art ${scene.art}`}><span>{scene.title}</span></div><figcaption><b>{scene.title}</b><small>{scene.description}</small></figcaption></button>)}</div><div className="control-group"><label>改编幅度</label><div className="segmented">{["忠于梦境","合理补全","自由改编"].map(x=><button className={adaptation===x?"active":""} key={x} onClick={()=>setAdaptation(x)}>{x}</button>)}</div></div><div className="control-group"><label>视觉风格</label><select className="style-select" value={style} onChange={e=>setStyle(e.target.value)} aria-label="视觉风格"><option>梦幻电影感</option><option>超现实主义</option><option>国风水墨</option><option>写实摄影</option><option>手绘动画</option></select></div><div className="control-group"><label>画面比例</label><div className="segmented">{["16:9","9:16","1:1"].map(x=><button className={ratio===x?"active":""} key={x} onClick={()=>setRatio(x)}>{x}</button>)}</div></div><button className="primary-button" onClick={generate} disabled={generating}>{generating?"正在提炼梦境画面…":"生成画面草图"}</button>{generating&&<div className="generation"><small>正在组合：{scenes[selected].title} · {style} · {adaptation}</small><div className="generation-bar"><i/></div></div>}{done&&<><div className={`output-art ${scenes[selected].art}`}><div><b>{scenes[selected].title}</b><span>{scenes[selected].description}</span><small>{style} · {ratio} · 本机梦境画面预览</small></div></div><button className="download-button" onClick={()=>{downloadDreamArtwork(dream,scenes[selected],style,ratio);notify("梦境画面已导出为 PNG")}}>下载 PNG 画面</button></>}</div><aside className="studio-aside"><h3>本梦创作圣经</h3><div className="bible-item"><small>作品标题</small><p>{dream.title}</p></div><div className="bible-item"><small>核心意象</small><p>{dream.analysis.symbols.map(s=>s.name).join("、")||dream.tags.join("、")}</p></div><div className="bible-item"><small>情绪基调</small><p>{dream.emotion}；主题为{dream.analysis.theme}</p></div><div className="bible-item"><small>原始边界</small><p>{dream.summary}</p></div></aside></div>}
function NovelStudio({dream,notify}:{dream:Dream;notify:(m:string)=>void}){const [tone,setTone]=useState("奇幻心理"),[expanded,setExpanded]=useState(false);const scenes=creativeScenes(dream);const opening=`${scenes[0].description}。醒来以前，“我”仍不知道${scenes[1].title}究竟在等待什么。于是，梦里的道路继续向${scenes[2].title}延伸。`;return <div className="novel-layout"><aside className="chapter-list"><button className="chapter-item active">00 · 故事梗概 ✓</button>{scenes.map((s,i)=><button className="chapter-item" key={s.title}>{String(i+1).padStart(2,"0")} · {s.title}</button>)}</aside><article className="novel-editor"><div className="report-label">{tone}短篇 · 根据当前梦境改编</div><h2>《{dream.title}》</h2><p>{opening}</p>{expanded&&<><p>{dream.content}</p><p>现实的逻辑逐渐退到远处，梦中的每个意象开始拥有自己的方向。主人公必须决定：跟随它，还是在醒来前留下一个新的结局。</p></>}<div className="evidence">艺术延展标记：新增叙述、人物动机与结局不属于原始梦境。</div><div className="creative-actions"><select value={tone} onChange={e=>setTone(e.target.value)} aria-label="小说风格"><option>奇幻心理</option><option>悬疑</option><option>温柔治愈</option><option>超现实</option></select><button onClick={()=>{setExpanded(true);notify("已根据当前梦境扩写第一章")}}>生成第一章</button><button onClick={async()=>{await navigator.clipboard.writeText(`${opening}\n\n${expanded?dream.content:""}`);notify("小说文本已复制")}}>复制文本</button></div></article></div>}
function FilmStudio({dream,notify}:{dream:Dream;notify:(m:string)=>void}){const scenes=creativeScenes(dream),[selected,setSelected]=useState(0),[queued,setQueued]=useState(false);return <><div className="film-logline"><small>电影梗概 · 梦境短片 / 约 3 分钟</small><h2>{dream.summary}。主人公必须穿过“{dream.analysis.theme}”的情绪，才能在醒来前理解最后一个画面。</h2></div><div className="studio-main"><div className="studio-title"><h3>分镜预览</h3><small>全部取自当前梦境</small></div><div className="shots">{scenes.concat([{title:"醒来",description:`带着“${dream.emotion}”回到现实`,art:"art-dawn"}]).map((shot,i)=><button className={`shot ${selected===i?"selected":""}`} key={shot.title} onClick={()=>setSelected(i)}><div className={`shot-art ${shot.art}`}><span>{String(i+1).padStart(2,"0")}</span></div><figcaption>{shot.title}<br/><small>{shot.description}</small></figcaption></button>)}</div><button className="primary-button" onClick={()=>{setQueued(true);notify("已生成当前分镜的视频提示词与镜头参数")}}>生成选中分镜方案</button>{queued&&<div className="video-plan"><b>镜头 {selected+1} · {selected<scenes.length?scenes[selected].title:"醒来"}</b><p>6 秒缓慢推进，保留“{dream.emotion}”的情绪基调；人物默认去识别化。当前提供可用的分镜与视频提示词预览，未连接外部视频模型。</p></div>}</div></>}
function LibraryPage(props:{dreams:Dream[];query:string;setQuery:(v:string)=>void;openDream:(d:Dream)=>void;}){return <section className="page"><div className="page-title"><div className="eyebrow">你的私人梦境档案</div><h1>梦册</h1><p>搜索人物、场景、情绪或梦象。</p></div><input className="search" value={props.query} onChange={e=>props.setQuery(e.target.value)} placeholder="搜索梦境" aria-label="搜索梦境"/><div className="library-list">{props.dreams.map(d=><button key={d.id} onClick={()=>props.openDream(d)}><span><b>{new Date(d.timestamp).getDate()}</b><small>{new Date(d.timestamp).getMonth()+1}月</small></span><span><h3>{d.title}</h3><p>{d.emotion} · {d.tags.join("、")}</p></span><i>›</i></button>)}{!props.dreams.length&&<div className="empty-card">没有找到匹配的梦境。</div>}</div></section>}
function InsightsPage({dreams}:{dreams:Dream[]}){const tagCounts=dreams.flatMap(d=>d.tags).reduce<Record<string,number>>((a,t)=>{a[t]=(a[t]||0)+1;return a;},{}),topTags=Object.entries(tagCounts).sort((a,b)=>b[1]-a[1]).slice(0,6),emotions=dreams.reduce<Record<string,number>>((a,d)=>{a[d.emotion]=(a[d.emotion]||0)+1;return a;},{});return <section className="page"><div className="page-title"><div className="eyebrow">看见反复出现的线索</div><h1>长期洞察</h1><p>统计只来自你真实保存的梦境。</p></div><div className="insight-hero"><small>当前档案</small><h2>已记录 {dreams.length} 个梦</h2><p>{dreams.length<3?"再多记录几次，重复意象会变得更清晰。":"下面是近期最常出现的梦象与感受。"}</p></div><div className="insight-grid"><div className="panel"><h3>高频梦象</h3>{topTags.length?topTags.map(([tag,count])=><div className="bar-row" key={tag}><span>{tag}</span><i style={{width:`${Math.max(18,count/Math.max(1,dreams.length)*100)}%`}}/><b>{count}</b></div>):<p>还没有足够数据。</p>}</div><div className="panel"><h3>醒来感受</h3>{Object.entries(emotions).map(([name,count])=><div className="emotion-row" key={name}><span>{name}</span><b>{count} 次</b></div>)}</div></div></section>}
function SettingsPage({dreamCount,clearAll}:{dreamCount:number;clearAll:()=>void;}){return <section className="page"><div className="page-title"><div className="eyebrow">隐私与使用说明</div><h1>设置</h1><p>当前版本把梦境保存在这台设备的浏览器中。</p></div><div className="settings-card"><div><b>本机梦境</b><span>{dreamCount} 条</span></div><div><b>语音输入</b><span>使用浏览器实时语音识别；不会填入演示文案</span></div><div><b>梦境分析</b><span>根据每条梦的原文、意象与感受即时生成</span></div><div><b>自动命名</b><span>从梦中人物、场景与动作归纳标题</span></div></div><button className="delete-button" onClick={clearAll}>清空这台设备上的全部数据</button></section>}

